const specialties = [
  "Bipolar",
  "LGBTQ",
  "Medication/Prescribing",
  "Suicide History/Attempts",
  "General Mental Health (anxiety, depression, stress, grief, life transitions)",
  "Men's issues",
  "Relationship Issues (family, friends, couple, etc)",
  "Trauma & PTSD",
  "Personality disorders",
  "Personal growth",
  "Substance use/abuse",
  "Pediatrics",
  "Women's issues (post-partum, infertility, family planning)",
  "Chronic pain",
  "Weight loss & nutrition",
  "Eating disorders",
  "Diabetic Diet and nutrition",
  "Coaching (leadership, career, academic and wellness)",
  "Life coaching",
  "Obsessive-compulsive disorders",
  "Neuropsychological evaluations & testing (ADHD testing)",
  "Attention and Hyperactivity (ADHD)",
  "Sleep issues",
  "Schizophrenia and psychotic disorders",
  "Learning disorders",
  "Domestic abuse",
];

const randomSpecialty = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2];
};

const names = [
  { firstName: "Olivia", lastName: "Williams" },
  { firstName: "Liam", lastName: "Johnson" },
  { firstName: "Emma", lastName: "Brown" },
  { firstName: "Noah", lastName: "Jones" },
  { firstName: "Ava", lastName: "Garcia" },
  { firstName: "Elijah", lastName: "Martinez" },
  { firstName: "Sophia", lastName: "Davis" },
  { firstName: "Lucas", lastName: "Rodriguez" },
  { firstName: "Mia", lastName: "Hernandez" },
  { firstName: "Mason", lastName: "Lopez" },
  { firstName: "Isabella", lastName: "Gonzalez" },
  { firstName: "William", lastName: "Perez" },
  { firstName: "Aiden", lastName: "Sanchez" },
  { firstName: "Sofia", lastName: "Torres" },
  { firstName: "Ethan", lastName: "Ramirez" },
  { firstName: "Aria", lastName: "Flores" },
  { firstName: "Jacob", lastName: "Gomez" },
  { firstName: "Avery", lastName: "Rivera" },
  { firstName: "Chloe", lastName: "Ortiz" },
  { firstName: "Ryan", lastName: "Gutierrez" },
  { firstName: "Aaliyah", lastName: "Cruz" },
  { firstName: "Ezra", lastName: "Nguyen" },
  { firstName: "Lila", lastName: "Hernandez" },
  { firstName: "Caleb", lastName: "Lopez" },
  { firstName: "Aria", lastName: "Garcia" },
  { firstName: "Samuel", lastName: "Martinez" },
  { firstName: "Hannah", lastName: "Rodriguez" },
  { firstName: "Oliver", lastName: "Garcia" },
  { firstName: "Charlotte", lastName: "Smith" },
  { firstName: "James", lastName: "Johnson" },
  { firstName: "Amelia", lastName: "Brown" },
  { firstName: "Benjamin", lastName: "Jones" },
  { firstName: "Harper", lastName: "Garcia" },
  { firstName: "Alexander", lastName: "Martinez" },
  { firstName: "Evelyn", lastName: "Davis" },
  { firstName: "Michael", lastName: "Rodriguez" },
  { firstName: "Abigail", lastName: "Hernandez" },
  { firstName: "Daniel", lastName: "Lopez" },
  { firstName: "Ella", lastName: "Gonzalez" },
  { firstName: "Matthew", lastName: "Perez" },
  { firstName: "Scarlett", lastName: "Sanchez" },
  { firstName: "Henry", lastName: "Torres" },
  { firstName: "Grace", lastName: "Ramirez" },
  { firstName: "Jackson", lastName: "Flores" },
  { firstName: "Victoria", lastName: "Gomez" },
  { firstName: "Sebastian", lastName: "Rivera" },
  { firstName: "Zoey", lastName: "Ortiz" },
  { firstName: "Jack", lastName: "Gutierrez" },
  { firstName: "Luna", lastName: "Cruz" },
  { firstName: "Owen", lastName: "Nguyen" },
  { firstName: "Mila", lastName: "Hernandez" },
  { firstName: "Levi", lastName: "Lopez" },
  { firstName: "Lily", lastName: "Garcia" },
  { firstName: "David", lastName: "Martinez" },
  { firstName: "Emily", lastName: "Rodriguez" },
  { firstName: "Joseph", lastName: "Garcia" },
  { firstName: "Samantha", lastName: "Smith" },
  { firstName: "Logan", lastName: "Johnson" },
  { firstName: "Natalie", lastName: "Brown" },
  { firstName: "Lucas", lastName: "Jones" },
  { firstName: "Zoe", lastName: "Garcia" },
  { firstName: "Isaac", lastName: "Martinez" },
  { firstName: "Penelope", lastName: "Davis" },
  { firstName: "Gabriel", lastName: "Rodriguez" },
  { firstName: "Riley", lastName: "Hernandez" },
  { firstName: "Anthony", lastName: "Lopez" },
  { firstName: "Nora", lastName: "Gonzalez" },
  { firstName: "Andrew", lastName: "Perez" },
  { firstName: "Hazel", lastName: "Sanchez" },
  { firstName: "Joshua", lastName: "Torres" },
  { firstName: "Violet", lastName: "Ramirez" },
  { firstName: "Christopher", lastName: "Flores" },
  { firstName: "Aurora", lastName: "Gomez" },
  { firstName: "Thomas", lastName: "Rivera" },
  { firstName: "Savannah", lastName: "Ortiz" },
  { firstName: "Charles", lastName: "Gutierrez" },
  { firstName: "Stella", lastName: "Cruz" },
  { firstName: "Eli", lastName: "Nguyen" },
  { firstName: "Paisley", lastName: "Hernandez" },
  { firstName: "Hunter", lastName: "Lopez" },
  { firstName: "Addison", lastName: "Garcia" },
  { firstName: "Christian", lastName: "Martinez" },
  { firstName: "Lucy", lastName: "Rodriguez" },
  { firstName: "Jonathan", lastName: "Garcia" },
  { firstName: "Brooklyn", lastName: "Smith" },
  { firstName: "Connor", lastName: "Johnson" },
  { firstName: "Bella", lastName: "Brown" },
  { firstName: "Aaron", lastName: "Jones" },
  { firstName: "Layla", lastName: "Garcia" },
  { firstName: "Cameron", lastName: "Martinez" },
  { firstName: "Aubrey", lastName: "Davis" },
  { firstName: "Adrian", lastName: "Rodriguez" },
  { firstName: "Hannah", lastName: "Hernandez" },
  { firstName: "Evan", lastName: "Lopez" },
  { firstName: "Madison", lastName: "Gonzalez" },
  { firstName: "Isaiah", lastName: "Perez" },
  { firstName: "Scarlett", lastName: "Sanchez" },
  { firstName: "Jordan", lastName: "Torres" },
  { firstName: "Avery", lastName: "Ramirez" },
  { firstName: "Brayden", lastName: "Flores" },
  { firstName: "Lillian", lastName: "Gomez" },
  { firstName: "Caleb", lastName: "Rivera" },
  { firstName: "Sofia", lastName: "Ortiz" },
  { firstName: "Nathan", lastName: "Gutierrez" },
  { firstName: "Ellie", lastName: "Cruz" },
  { firstName: "Dylan", lastName: "Nguyen" },
  { firstName: "Maya", lastName: "Hernandez" },
  { firstName: "Henry", lastName: "Lopez" },
  { firstName: "Chloe", lastName: "Garcia" },
  { firstName: "Sebastian", lastName: "Martinez" },
  { firstName: "Grace", lastName: "Rodriguez" },
  { firstName: "Jackson", lastName: "Garcia" },
  { firstName: "Victoria", lastName: "Smith" },
  { firstName: "Levi", lastName: "Johnson" },
  { firstName: "Zoey", lastName: "Brown" },
  { firstName: "Jack", lastName: "Jones" },
  { firstName: "Luna", lastName: "Garcia" },
  { firstName: "Owen", lastName: "Martinez" },
  { firstName: "Mila", lastName: "Davis" },
  { firstName: "Lily", lastName: "Rodriguez" },
  { firstName: "David", lastName: "Hernandez" },
  { firstName: "Emily", lastName: "Lopez" },
  { firstName: "Joseph", lastName: "Gonzalez" },
  { firstName: "Samantha", lastName: "Perez" },
  { firstName: "Logan", lastName: "Sanchez" },
  { firstName: "Natalie", lastName: "Torres" },
  { firstName: "Lucas", lastName: "Ramirez" },
  { firstName: "Zoe", lastName: "Flores" },
  { firstName: "Isaac", lastName: "Gomez" },
  { firstName: "Penelope", lastName: "Rivera" },
  { firstName: "Gabriel", lastName: "Ortiz" },
  { firstName: "Riley", lastName: "Gutierrez" },
  { firstName: "Anthony", lastName: "Cruz" },
  { firstName: "Nora", lastName: "Nguyen" },
  { firstName: "Andrew", lastName: "Hernandez" },
  { firstName: "Hazel", lastName: "Lopez" },
  { firstName: "Joshua", lastName: "Garcia" },
  { firstName: "Violet", lastName: "Martinez" },
  { firstName: "Christopher", lastName: "Rodriguez" },
  { firstName: "Aurora", lastName: "Garcia" },
  { firstName: "Thomas", lastName: "Smith" },
  { firstName: "Savannah", lastName: "Johnson" },
  { firstName: "Charles", lastName: "Brown" },
  { firstName: "Stella", lastName: "Jones" },
  { firstName: "Eli", lastName: "Garcia" },
  { firstName: "Paisley", lastName: "Martinez" },
  { firstName: "Hunter", lastName: "Davis" },
  { firstName: "Addison", lastName: "Rodriguez" },
  { firstName: "Christian", lastName: "Hernandez" },
  { firstName: "Lucy", lastName: "Lopez" },
  { firstName: "Jonathan", lastName: "Gonzalez" },
  { firstName: "Brooklyn", lastName: "Perez" },
  { firstName: "Connor", lastName: "Sanchez" },
  { firstName: "Bella", lastName: "Torres" },
  { firstName: "Aaron", lastName: "Ramirez" },
  { firstName: "Layla", lastName: "Flores" },
  { firstName: "Cameron", lastName: "Gomez" },
  { firstName: "Aubrey", lastName: "Rivera" },
  { firstName: "Adrian", lastName: "Ortiz" },
  { firstName: "Hannah", lastName: "Gutierrez" },
  { firstName: "Evan", lastName: "Cruz" },
  { firstName: "Madison", lastName: "Nguyen" },
  { firstName: "Isaiah", lastName: "Hernandez" },
  { firstName: "Scarlett", lastName: "Lopez" },
  { firstName: "Jordan", lastName: "Garcia" },
  { firstName: "Avery", lastName: "Martinez" },
  { firstName: "Brayden", lastName: "Rodriguez" },
  { firstName: "Lillian", lastName: "Garcia" },
  { firstName: "Caleb", lastName: "Smith" },
  { firstName: "Sofia", lastName: "Johnson" },
  { firstName: "Nathan", lastName: "Brown" },
  { firstName: "Ellie", lastName: "Jones" },
  { firstName: "Dylan", lastName: "Garcia" },
  { firstName: "Maya", lastName: "Martinez" },
  { firstName: "Henry", lastName: "Davis" },
  { firstName: "Chloe", lastName: "Rodriguez" },
  { firstName: "Sebastian", lastName: "Hernandez" },
  { firstName: "Grace", lastName: "Lopez" },
  { firstName: "Jackson", lastName: "Gonzalez" },
  { firstName: "Victoria", lastName: "Perez" },
  { firstName: "Levi", lastName: "Sanchez" },
  { firstName: "Zoey", lastName: "Torres" },
  { firstName: "Jack", lastName: "Ramirez" },
  { firstName: "Luna", lastName: "Flores" },
  { firstName: "Owen", lastName: "Gomez" },
  { firstName: "Mila", lastName: "Rivera" },
  { firstName: "Lily", lastName: "Ortiz" },
  { firstName: "David", lastName: "Gutierrez" },
  { firstName: "Emily", lastName: "Cruz" },
  { firstName: "Joseph", lastName: "Nguyen" },
  { firstName: "Samantha", lastName: "Hernandez" },
  { firstName: "Logan", lastName: "Lopez" },
  { firstName: "Natalie", lastName: "Garcia" },
  { firstName: "Lucas", lastName: "Martinez" },
  { firstName: "Zoe", lastName: "Rodriguez" },
  { firstName: "Isaac", lastName: "Garcia" },
  { firstName: "Penelope", lastName: "Smith" },
  { firstName: "Gabriel", lastName: "Johnson" },
  { firstName: "Riley", lastName: "Brown" },
  { firstName: "Anthony", lastName: "Jones" },
  { firstName: "Nora", lastName: "Garcia" },
  { firstName: "Andrew", lastName: "Martinez" },
  { firstName: "Hazel", lastName: "Davis" },
  { firstName: "Joshua", lastName: "Rodriguez" },
  { firstName: "Violet", lastName: "Hernandez" },
  { firstName: "Christopher", lastName: "Lopez" },
  { firstName: "Aurora", lastName: "Gonzalez" },
  { firstName: "Thomas", lastName: "Perez" },
  { firstName: "Savannah", lastName: "Sanchez" },
  { firstName: "Charles", lastName: "Torres" },
  { firstName: "Stella", lastName: "Ramirez" },
  { firstName: "Eli", lastName: "Flores" },
  { firstName: "Paisley", lastName: "Gomez" },
  { firstName: "Hunter", lastName: "Rivera" },
  { firstName: "Addison", lastName: "Ortiz" },
  { firstName: "Christian", lastName: "Gutierrez" },
  { firstName: "Lucy", lastName: "Cruz" },
  { firstName: "Jonathan", lastName: "Nguyen" },
  { firstName: "Brooklyn", lastName: "Hernandez" },
  { firstName: "Connor", lastName: "Lopez" },
  { firstName: "Bella", lastName: "Garcia" },
  { firstName: "Aaron", lastName: "Martinez" },
  { firstName: "Layla", lastName: "Rodriguez" },
  { firstName: "Cameron", lastName: "Garcia" },
  { firstName: "Aubrey", lastName: "Smith" },
  { firstName: "Adrian", lastName: "Johnson" },
  { firstName: "Hannah", lastName: "Brown" },
  { firstName: "Evan", lastName: "Jones" },
  { firstName: "Madison", lastName: "Garcia" },
  { firstName: "Isaiah", lastName: "Martinez" },
  { firstName: "Scarlett", lastName: "Davis" },
  { firstName: "Jordan", lastName: "Rodriguez" },
  { firstName: "Avery", lastName: "Hernandez" },
  { firstName: "Brayden", lastName: "Lopez" },
  { firstName: "Lillian", lastName: "Gonzalez" },
  { firstName: "Caleb", lastName: "Perez" },
  { firstName: "Sofia", lastName: "Sanchez" },
  { firstName: "Nathan", lastName: "Torres" },
  { firstName: "Ellie", lastName: "Ramirez" },
  { firstName: "Dylan", lastName: "Flores" },
  { firstName: "Maya", lastName: "Gomez" },
  { firstName: "Henry", lastName: "Rivera" },
  { firstName: "Chloe", lastName: "Ortiz" },
  { firstName: "Sebastian", lastName: "Gutierrez" },
  { firstName: "Grace", lastName: "Cruz" },
  { firstName: "Jackson", lastName: "Nguyen" },
  { firstName: "Victoria", lastName: "Hernandez" },
  { firstName: "Levi", lastName: "Lopez" },
  { firstName: "Zoey", lastName: "Garcia" },
  { firstName: "Jack", lastName: "Martinez" },
  { firstName: "Luna", lastName: "Rodriguez" },
  { firstName: "Owen", lastName: "Garcia" },
  { firstName: "Mila", lastName: "Smith" },
  { firstName: "Lily", lastName: "Johnson" },
  { firstName: "David", lastName: "Brown" },
  { firstName: "Emily", lastName: "Jones" },
  { firstName: "Joseph", lastName: "Garcia" },
  { firstName: "Samantha", lastName: "Martinez" },
  { firstName: "Logan", lastName: "Davis" },
  { firstName: "Natalie", lastName: "Rodriguez" },
  { firstName: "Lucas", lastName: "Hernandez" },
  { firstName: "Zoe", lastName: "Lopez" },
  { firstName: "Isaac", lastName: "Gonzalez" },
  { firstName: "Penelope", lastName: "Perez" },
  { firstName: "Gabriel", lastName: "Sanchez" },
  { firstName: "Riley", lastName: "Torres" },
  { firstName: "Anthony", lastName: "Ramirez" },
  { firstName: "Nora", lastName: "Flores" },
  { firstName: "Andrew", lastName: "Gomez" },
  { firstName: "Hazel", lastName: "Rivera" },
  { firstName: "Joshua", lastName: "Ortiz" },
  { firstName: "Violet", lastName: "Gutierrez" },
  { firstName: "Christopher", lastName: "Cruz" },
  { firstName: "Aurora", lastName: "Nguyen" },
  { firstName: "Thomas", lastName: "Hernandez" },
  { firstName: "Savannah", lastName: "Lopez" },
  { firstName: "Charles", lastName: "Garcia" },
  { firstName: "Stella", lastName: "Martinez" },
  { firstName: "Eli", lastName: "Rodriguez" },
  { firstName: "Paisley", lastName: "Garcia" },
  { firstName: "Hunter", lastName: "Smith" },
  { firstName: "Addison", lastName: "Johnson" },
  { firstName: "Christian", lastName: "Brown" },
  { firstName: "Lucy", lastName: "Jones" },
  { firstName: "Jonathan", lastName: "Garcia" },
  { firstName: "Brooklyn", lastName: "Martinez" },
  { firstName: "Connor", lastName: "Davis" },
  { firstName: "Bella", lastName: "Rodriguez" },
  { firstName: "Aaron", lastName: "Hernandez" },
  { firstName: "Layla", lastName: "Lopez" },
  { firstName: "Cameron", lastName: "Gonzalez" },
  { firstName: "Aubrey", lastName: "Perez" },
  { firstName: "Adrian", lastName: "Sanchez" },
  { firstName: "Hannah", lastName: "Torres" },
  { firstName: "Evan", lastName: "Ramirez" },
  { firstName: "Madison", lastName: "Flores" },
  { firstName: "Isaiah", lastName: "Gomez" },
  { firstName: "Scarlett", lastName: "Rivera" },
  { firstName: "Jordan", lastName: "Ortiz" },
  { firstName: "Avery", lastName: "Gutierrez" },
];

const cities = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Charlotte",
];

const additionalAdvocates = Array.from({ length: 300 }, (_, index) => ({
  firstName: names[index % names.length].firstName,
  lastName: names[index % names.length].lastName,
  city: cities[index % cities.length],
  degree: ["MD", "PhD", "MSW"][index % 3],
  specialties: specialties.slice(...randomSpecialty()),
  yearsOfExperience: Math.floor(Math.random() * 20) + 1,
  phoneNumber: 5550000000 + index,
}));

const advocateData = [
  {
    firstName: "John",
    lastName: "Doe",
    city: "New York",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551234567,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    city: "Los Angeles",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: 5559876543,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    city: "Chicago",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5554567890,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    city: "Houston",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: 5556543210,
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    city: "Phoenix",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: 5553210987,
  },
  {
    firstName: "Chris",
    lastName: "Martinez",
    city: "Philadelphia",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5557890123,
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    city: "San Antonio",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: 5554561234,
  },
  {
    firstName: "David",
    lastName: "Harris",
    city: "San Diego",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: 5557896543,
  },
  {
    firstName: "Laura",
    lastName: "Clark",
    city: "Dallas",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: 5550123456,
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    city: "San Jose",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: 5553217654,
  },
  {
    firstName: "Sarah",
    lastName: "Lee",
    city: "Austin",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: 5551238765,
  },
  {
    firstName: "James",
    lastName: "King",
    city: "Jacksonville",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: 5556540987,
  },
  {
    firstName: "Megan",
    lastName: "Green",
    city: "San Francisco",
    degree: "MD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: 5559873456,
  },
  {
    firstName: "Joshua",
    lastName: "Walker",
    city: "Columbus",
    degree: "PhD",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: 5556781234,
  },
  {
    firstName: "Amanda",
    lastName: "Hall",
    city: "Fort Worth",
    degree: "MSW",
    specialties: specialties.slice(...randomSpecialty()),
    yearsOfExperience: 3,
    phoneNumber: 5559872345,
  },
  ...additionalAdvocates,
];

export { advocateData };
